### ISSUE TITLE
What about database.yml?

### ISSUE THREAD

**Issue by ledermann** [capistrano-plugins/capistrano-secrets-yml#2]
In a typical Rails application there is a `database.yml` file, which should be handled the same as `secrets.yml`. Creating another plugin (like "capistrano-database-yml") seems to be odd, what about enhancing this repo to handle both yaml files?

**Comment by bruno-** [comment]
Hey,
I've never really thought about extending this plugin with additional `yml` files.. Currently there's a [capistrano-postgresql](https://github.com/capistrano-plugins/capistrano-postgresql) that handles `database.yml` creation (among other things) for postgres. Maybe you wanna give that one a shot?

I'll close this issue but feel free to reopen if you have additional comments or ideas.

**Comment by ConfusedVorlon** [comment]
@ledermann 
You can just access the secrets.yml values directly in database.yml

```
production:
  <<: *default
  database: db_name
  username: user_name
  password: <%= Rails.application.secrets.db_password %>
```
